### PR TITLE
Removed DeepReadonly limitation on non-function keys to fix optional …

### PR DESCRIPTION
**Pull request by piotrwitek**
Removed DeepReadonly limitation on non-function keys to fix optional keys marked as required

### CODE REVIEW

**Comment by ajhyndman** [comment]
Thanks for finding the workaround here, @piotrwitek.  I think this change makes sense!

I am curious though: can you explain what was broken when changing `{ ... }[keyof T]` to `key of { ... }`?

**Comment by piotrwitek** [comment]
Behaviour of the particular type was broken, it was supposed to be narrowed by `keyof T` and not expanded by `key of`

**Comment by FrimJo** [comment]
Thnx for a nice update! I see that is has been merged with master, when will it see the light of day?

**Comment by piotrwitek** [comment]
I'll try to release a new package today/tomorrow.

**Pull request merged**
