### PR TITLE
Update mapped-types.ts

### PR DESCRIPTION
**Pull request by RayLuxembourg**
Never mind we have $keys

### CODE REVIEW

**Comment by piotrwitek** [comment]
Hey @RayLuxembourg,
Even though we have $keys I would still accept this change because it adds an alias to stay consistent with TS conventions.

One change I would like to rename it to just `Keys`. Otherwise looks good to merge.

**Comment by levenleven** [comment]
Maybe I'm missing something, but what's the difference with standard `keyof Foo`?

**Comment by RayLuxembourg** [comment]
@piotrwitek I have changed the name to keys and reopened the pull request

**Comment by levenleven** [comment]
@RayLuxembourg could you explain why it is not just:
```typescript
type Keys<T extends object> = keyof T
```
Also not sure why would we need object constraint

**Comment by piotrwitek** [comment]
@levenleven sorry for the confusion, actually you are right.
I was actually thinking about something else, a `Values` type, but I rushed too much without thinking.

Here is what I was thinking about:
```ts
export type ValueType<T extends any[] | Record<string, any>> = T extends any[]
  ? T[number]
  : T extends Record<string, any>
  ? { [K in keyof T]: T[K] extends any ? T[K] : never }[keyof T]
  : never;

const arr = [1, 2];
const obj = { key: 'value' };

type t1 = typeof arr[number];
type t2 = typeof obj[keyof typeof obj]; // this is really mouthful and I was annoyed by this many times

// consistent and simple
type t3 = ValueType<typeof arr>; // number
type t4 = ValueType<typeof obj>; // string
```

What you think now?

**Comment by RayLuxembourg** [comment]
> @RayLuxembourg could you explain why it is not just:
> 
> ```ts
> type Keys<T extends object> = keyof T
> ```
> 
> Also not sure why would we need object constraint

You are right.

**Comment by piotrwitek** [comment]
Still missing:
For new features:
* [ ] I have added entry in TOC and API Docs
* [ ] I have added a short example in API Docs to demonstrate new usage
* [ ] I have added type unit tests with `dts-jest`

**Comment by piotrwitek** [comment]
Closing as it's not that useful I guess

**Pull request closed without merging**
