### PR TITLE
WIP: Add type guards

### LINKED ISSUE #88: Add type guards for some simple types
## Is your feature request related to a real problem or use-case?
Yes. Type guards are a nice solution for type-flow in typescript.

## Describe a solution including usage in code example
```ts
const isPrimitive = (val: unknown): val is Primitive => {
    switch (typeof val) {
        case 'string':
        case 'symbol':
        case 'number':
        case 'bigint':
        case 'boolean': {
            return true;
        }
        default: return false;
    }
};

const isFalsey = (val: unknown): val is Falsey => !val;

const valConsumer =  (testVal: unknown) => {
    if (!isPrimitive(testVal)) {
         // do stuff
        return 'isComplex';
    }
    type TestVal = typeof testVal; // == Primitive
    // do stuff
    return 'isPrimitive';
};
```

## Who does this impact? Who is this for?
All the users that have to support a more universal API and want to test for specific usecases with immediate TS support without explicit casting or having to write their own type guards.

## Additional context (optional)
* [Official Documentation for Type Guards in TS](https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-guards-and-differentiating-types)

### PR DESCRIPTION
**Pull request by 9SMTM6**
## Description
Added type guards for Primitive and Falsey

This relies on the addition of bigInt to Primitive as in merge request #87 and should only be merged after that. As long as said merge request is unmerged there might be more stuff in these diffs than explained with this specific merge request.

If anyone wants to add the documentation feel free to, else I'll get back to it eventually.

## Related issues:
- Resolved #88 

## Checklist

* [x] I have read [CONTRIBUTING.md](../CONTRIBUTING.md)
* [x] I have linked all related issues above
* [ ] I have rebased my branch

For new features:
* [x] I have added entry in TOC and API Docs
* [x] I have added a short example in API Docs to demonstrate new usage
* [x] I have added type unit tests with `dts-jest`

### CODE REVIEW

**Comment by piotrwitek** [comment]
Hey @9SMTM6, what is the status of this PR, when do you think you'll be able to finish it?
I'll be happy to merge it.

Please remember to rebase.

**Comment by 9SMTM6** [comment]
Hello @piotrwitek and thanks for asking. 

I have not forgotten about this, just that it's been somewhat busy of late with me searching for a topic for my thesis (harder than I hoped to find a topic which I like that combines informatics and physics, mostly machine learning stuff which isn't that common in my University) and exams coming up, while at the same time changing projects at my workplace.

I'm also not entirely sure why the test was failing, I cant seem to be able to look up the logs anywhere? And back then there was no merge conflict.

Considering when I can get back to it, well once I get a bit of breathing room, which probably won't be before Friday or the Weekend. Feel free to hijack this merge request to finish the work (you should be able to no?) if you have the time. I'd love to see the changes in that case and should you wish so could do a code review ASAP.

Otherwise, as said I'll probably get to it this Weekend but I can't guarantee that, and some help on where I can look up the test logs or why the tests failed would be appreciated.

**Comment by 9SMTM6** [comment]
But I'll quickly pull it up to the newest version so the diff gets reduced to the changes I did so far.

**Comment by 9SMTM6** [comment]
And as added before the tests were running locally

**Comment by 9SMTM6** [comment]
@piotrwitek 

Okay, think I found the error (didnt commit the snapshot file, guess i did 'commit -am "[...]"' and forgot I added a new file).

Think I'll quickly finish this up

**Comment by 9SMTM6** [comment]
@piotrwitek So. All tests written, Readme added, tests run both locally and online.

2 things remaining:

* As you may notice when reading the tests: As I suspected the snapshot tests dont correctly record snapshots for every one of the values in the array but only the last they ran. I'm not feeling like writing a test for every one of these test values myself though. Open for input

* I'm note entirely certain what you understand under `rebase`, but I believe either way I didnt do it exactly as you may wish. I'm aware of the `rebase` command, but unfortunately I merged before I was aware of the exact implications, so there will be merge commits in the history.

**Comment by 9SMTM6** [comment]
@piotrwitek any feedback on these points?

**Comment by piotrwitek** [comment]
@9SMTM6 thanks for all the effort, IMO it looks.
You did the merge operation instead of rebasing but it's still fine as the end result is the same although commit history would be cleaner. This doesn't make any difference to me as I'm squashing all the commits anyway.

Type tests for me looking good 👍

**Pull request merged**
