### PR TITLE
Deepreadonly should preserve optional keys

### PR DESCRIPTION
**Pull request by ajhyndman**
`DeepReadonly` as implemented right now has a side effect.  All optional keys are converted to required keys.  I think I found a small tweak to the implementation that allows us to preserve the optional key modifier!

I have added a couple test assertions that hopefully help clarify the issue I'm identifying.

### CODE REVIEW

**Comment by northerneyes** [comment]
I found a more easy way to do that using `Pick`

```ts
/**
 * NonFunctionKeys
 * @desc get union type of keys that are non-functions in object type `T`
 */
export type NonFunctionKeys<T> = Pick<
  T,
  keyof T extends Function ? never : keyof T
>
/**
 * DeepReadonlyObject
 * @desc Nested object condition handler
 * @private
 */
export type _DeepReadonlyObject<T> = {
  readonly [P in keyof NonFunctionKeys<T>]: DeepReadonly<T[P]>
}
```

**Comment by northerneyes** [comment]
You can use Pick as well to implement `NonFunctionKeys`
```ts
/**
 * NonFunctionKeys
 * @desc get union type of keys that are non-functions in object type `T`
 */
type NonFunctionKeys<T> = keyof Pick<
  T,
  keyof T extends Function ? never : keyof T
>
```

**Comment by piotrwitek** [comment]
Hey @ajhyndman, that's really cool!
I remember I was trying that but couldn't figure that one out, I'll check out your solution.

Does it work with TS v2.8?

**Comment by ajhyndman** [comment]
Yep, I've been using it with 2.8, 2.9 and now 3.0.

**Comment by serkandurusoy** [comment]
@piotrwitek do you plan on merging this? we've hit the same problem with it in our redux state and we had to manually apply this onto a local fork of your package. So far we're not having any problems and the optionality issue is resolved!

**Comment by FrimJo** [comment]
I'm too is looking forward to this update, any thoughts on when we can expect to see it live?

**Comment by piotrwitek** [comment]
Merging and releasing today

**Comment by piotrwitek** [comment]
Not merging, after close look this is not a fix at all, it has broken `FunctionKeys` and `NonFunctionKeys` types. To make it work it has to fix it without touching Public Api types

**Comment by piotrwitek** [comment]
I have another fix that doesn't break other API, but will change the behaviour of DeepReadonly.

Previously it was working only on non function keys, I don't remember rationale for it, but I think most of the time when using Readonly you would also want to have methods marked as readonly as well, no?

**Comment by piotrwitek** [comment]
New PR: https://github.com/piotrwitek/utility-types/pull/31

**Pull request merged**
